# Generated by Django 3.1.3 on 2020-11-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_pertence'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default='1', upload_to='documentos'),
            preserve_default=False,
        ),
    ]
